on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.md"
      - "**/compile_linux.yml"
      - "**/compile_windows.yml"
      - "**/build_flatpak.yml"
      - "**/.all-contributorsrc"
      - "**/windows_debug.yml"
      - "**/upload_binaries_to_draft.yml"
  pull_request:
    branches: [master]

name: Upload source with submodules
jobs:
  upload-full-src:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: Soundux

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake libx11-dev libpipewire-0.3-dev ninja-build libxi-dev libwnck-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev libpulse-dev"

      - name: Fetch Required External Dependencies
        run: 'cd Soundux && cmake -GNinja . && find build -not -name "_deps" -delete && rm CMakeCache.txt'

      - name: Create tarball
        uses: master-atul/tar-action@v1.0.2
        with:
          command: c
          files: |
            ./Soundux
          outPath: soundux.tar.gz

      - name: Upload
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Source tarball
          path: soundux.tar.gz
